version: '3'

services:
  nodeapp:
    build: .
    container_name: nodeapp
    labels:
      - "version=2.0"
      - "description=This is my Node.js app: backend_v2"
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_DB_PORT=mongodb://mongodb:27017/db
    depends_on:
      - mongodb

  angular:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: webapp
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
